Repository vishakha-lall/MapBot, pull requests merged in 2020-04, with the labels that each got.

#109 Integrate with Telegram #76 resolved
  .travis.yml
  ENV/.env
  README.md
  config.py
  telegram.py
Labels: gssoc20, hard

#80 Create symbolic names for learn_response #22 resolved
  chatbot.py
  databaseconnect.py
Labels: easy, gssoc20

#112 Add remaining tests and refactor URLs in googleMapsApiModule.py #106
  constants.py
  googleMapsApiModule.py
  test_googleMapsApiModule.py
Labels: easy, gssoc20

#111 Code Formatting #110 resolved
  .travis.yml
  app.py
  chatbot.py
  config.py
  constants.py
  databaseconnect.py
  features.py
  featuresDump.py
  googleMapsApiModule.py
  init.py
  logger_config.py
  requirements.txt
  telegram.py
  test_googleMapsApiModule.py
  utilities.py
Labels: gssoc20, medium

#118 Code formatting #117 resolved
  constants.py
  databaseconnect.py
  googleMapsApiModule.py
  test_databaseconnect.py
  test_googleMapsApiModule.py
Labels: easy, gssoc20

#119 Add unit-tests for utilities.py #75 resolved
  test_utilities.py
  utilities.py
Labels: gssoc20, medium

#108 Add different text classifiers to improve the user input classification_resolved
  chatbot.py
  requirements.txt
  utilities.py
Labels: gssoc20, hard

#93 Bugfix : Fix issue caused by converting SQL insert queries to f-strings without proper variable conversion (#62) resolved
  databaseconnect.py
Labels: gssoc20, medium

#121 Travis CI on test_databaseconnect.py doesn't work. #120 resolved
  .travis.yml
  databaseconnect.py
  googleMapsApiModule.py
  test_databaseconnect.py
  test_googleMapsApiModule.py
  test_utilities.py
  utilities.py
Labels: gssoc20, medium

#125 Add functionality to persist and retrain ML model #59 resolved
  chatbot.py
  model.joblib
Labels: gssoc20, hard

#127 Maintenance of PR quality #126 resolved
  .github/pull_request_template.md
  CONTRIBUTING.md
  GSSoC.md
  README.md
Labels: easy, gssoc20

#116 Gather more data for the chatbot's database via publicly available datasets_resolved
  analysis/sentences.csv
  analysis/sentences_new.csv
Labels: easy, gssoc20

#129 Prefering googlemaps object more than JSON #128 resolved
  googleMapsApiModule.py
  test_googleMapsApiModule.py
Labels: gssoc20, hard

#131 Change bot responses to something more informative #130 resolved
  chatbot.py
  googleMapsApiModule.py
  telegram.py
Labels: gssoc20, medium

#95 Integrate with Slack Bot #78 resolved
  ENV/.env
  README.md
  app.py
  config.py
  requirements.txt
  slackbot.py
Labels: gssoc20, hard

#137 Create a basic chatbot UI to replace init.py #17 resolved
  README.md
  requirements.txt
  templates/index.html
  webapp.py
Labels: gssoc20, hard

#139 Integrate elevation API call to bot response #135 resolved
  chatbot.py
  googleMapsApiModule.py
  init.py
  test_googleMapsApiModule.py
Labels: gssoc20, hard

#138 Integrate with Facebook Messenger #77_resolved
  ENV/.env
  README.md
  app.py
  config.py
  requirements.txt
Labels: gssoc20, hard

#144 Integrate timezone API call to bot response #132 resolved
  chatbot.py
  googleMapsApiModule.py
  test_googleMapsApiModule.py
Labels: gssoc20, hard

#143 Project testing on multiple Operating systems #141_Resolved
  .travis.yml
Labels: gssoc20, medium

#146 Checking all kinds of queries for possible GMapsAPI calls #145 resolved
  chatbot.py
  databaseconnect.py
Labels: gssoc20, medium
