Repository vishakha-lall/MapBot, pull requests merged in 2020-05, with the labels that each got.

#150 Integrate places API call to bot response #136 resolved
  chatbot.py
Labels: gssoc20, hard

#152 Need for test_chatbot.py #151 resolved
  .travis.yml
  CONTRIBUTING.md
  test_chatbot.py
Labels: gssoc20, medium

#159 Create supporting UI enhancements for suggestive questions #154 resolved
  static/js/sugg_button.js
  suggestive_chatbot.py
  templates/index.html
  webapp.py
Labels: gssoc20, hard

#162 Suggestive buttons UI improvement #160 resolved
  static/js/sugg_button.js
  templates/index.html
Labels: gssoc20, medium

#164 JS best practices #163 resolved
  static/js/sugg_button.js
  static/js/user_input.js
  templates/index.html
Labels: easy, gssoc20

#161 File to clear tables added.
  cleardb.py
  databaseconnect.py
Labels: easy, gssoc20

#166 Deployment using Docker. #165 resolved
  Dockerfile
  ENV/docker.env
  README.md
  chatbot.py
  docker-compose.yml
  docker-entrypoint.sh
  start.sh
  webapp.py
Labels: gssoc20, hard

#168 Use of spaCy instead of CoreNLP #167 resolved
  chatbot.py
  utilities.py
Labels: gssoc20, hard

#174 Docker deployment based on spaCy #171 resolved
  .dockerignore
  Dockerfile
  ENV/docker.env
  docker-compose.yml
  docker-entrypoint.sh
Labels: gssoc20, hard

#173 Documentation and dependency changes #170 resolved
  .gitignore
  ENV/.env
  README.md
  config.py
  requirements.txt
Labels: gssoc20, hard

#172 Handling location names with spaCy's NER #169 resolved
  chatbot.py
  utilities.py
Labels: gssoc20, hard

#176 pytests and Travis CI concerns #175 resolved
  chatbot.py
  test_utilities.py
  utilities.py
Labels: gssoc20, medium

#180 Travis CI for PostgreSQL #178 resolved
  .travis.yml
  databaseconnect.py
Labels: gssoc20, medium

#183 Updating Docker setup for PostgreSQL #182 resolved
  ENV/docker.env
  db-init/init.sql
  docker-compose.yml
  requirements.txt
Labels: gssoc20, hard

#185 Telegram bot hosted on cloud #184 resolved
  Procfile
  telegram.py
Labels: gssoc20, hard

#189 Documentation changes to update Heroku links #188 reoslved
  README.md
Labels: beginner, gssoc20

#191 Telegram webhook support #190 resolved
  Procfile
  README.md
  telegram.py
  webapp.py
Labels: gssoc20, hard

#193 Facebook bot hosted on cloud #192 resolved
  facebook.py
  telegram.py
  webapp.py
Labels: gssoc20, hard

#195 Clean code base after Messenger bot deployment #194 resolved
  GSSoC.md
  README.md
  app.py
  requirements.txt
Labels: gssoc20, hard

#197 databaseconnect.describe_table() not working #196 resolved
  cleardb.py
  databaseconnect.py
Labels: gssoc20, medium

#199 Heroku build log error #198 resolved
  .travis.yml
  nltk.txt
  runtime.txt
Labels: easy, gssoc20
