Repository vishakha-lall/MapBot, pull requests merged in 2020-03, with the labels that each got.

#40 Extract database related methods from utilities.py #26 resolved
  .gitignore
  chatbot.py
  config.py
  databaseconnect.py
  utilities.py
Labels: beginner, gssoc20

#39 requirements.txt problem solved #38
  .gitignore
  requirements.txt
Labels: beginner, gssoc20

#43 Add method to googleMapsApiModule.py for StaticMapsAPI #21 resolved
  googleMapsApiModule.py
Labels: gssoc20, medium

#41 Containerization of the app using docker-compose #13 resolved
  .dockerignore
  .gitignore
  Dockerfile
  config.py
  databaseconnect.py
  db-init/init.sql
  docker-compose.yml
  requirements.txt
  start.sh
Labels: gssoc20, hard

#48 Complete the documentation for containerised project #25 resolved
  README.md
Labels: beginner, good first issue, gssoc20

#42 Refactor redundant code in googleMapsApiModule.py #16 Resolved
  constants.py
  googleMapsApiModule.py
Labels: beginner, gssoc20

#50 Depreciate connections to database to store origin and destination before making API call #15 resolved
  chatbot.py
  googleMapsApiModule.py
Labels: easy, gssoc20

#51 Persist database and application volume in containerised application #14 resolved
  docker-compose.yml
Labels: gssoc20, medium

#54 Refactor string formatting in googleMapsApiModule.py #44 resolved
  googleMapsApiModule.py
Labels: beginner, gssoc20

#58 Create a method to clear database #24 resolved
  databaseconnect.py
Labels: gssoc20, medium

#60 Uniform path referencing that is compatible with all OS #28 Resolved
  featuresDump.py
  utilities.py
Labels: beginner, gssoc20

#63 Pathlib tempfix
  config.py
  databaseconnect.py
  utilities.py
Labels: bug

#55 Implement logging throughout the project #29 resolved
  chatbot.py
  databaseconnect.py
  features.py
  featuresDump.py
  googleMapsApiModule.py
  logger_config.py
  utilities.py
Labels: enhancement, gssoc20, medium

#65 Add method to googleMapsApiModule.py for ElevationAPI #20 resolved
  googleMapsApiModule.py
Labels: gssoc20, medium

#70 Fix to "Implement logging throughout the project #29"
  logger_config.py
Labels: bug

#72 Refactor module imports in all scripts #31 Resolved
  chatbot.py
Labels: easy, gssoc20

#71 Add pep8 linter for standardising code quality Resolved
  .gitignore
  chatbot.py
  config.py
  constants.py
  databaseconnect.py
  features.py
  googleMapsApiModule.py
  init.py
  logger_config.py
  requirements.txt
  utilities.py
Labels: gssoc20, medium

#81 Improve init.py to have a more organised structure and functionality #27 Resolved
  chatbot.py
  init.py
Labels: gssoc20, hard

#91 Add ISSUE_TEMPLATE.md_resolved
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
Labels: easy, gssoc20

#89 Add support for .env file #49 resolved
  .gitignore
  README.md
  config.py
  requirements.txt
  template.txt
Labels: easy, gssoc20

#84 Expose existing python3 functions as service endpoints _resolved
  .gitignore
  app.py
Labels: gssoc20, medium

#61 Add method to googleMapsApiModule.py for TimeZoneAPI #19 Resolved
  googleMapsApiModule.py
Labels: gssoc20, medium

#85 Add unit-tests for googleMapsApiModule.py #66 resolved
  googleMapsApiModule.py
  requirements.txt
  test_googleMapsApiModule.py
Labels: gssoc20, hard

#92 Add PULL_REQUEST_TEMPLATE.md_resolved
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: easy, gssoc20

#102 BugFix: Fix incorrect parameters in describe_table in module databaseconnect.py #101 resolved
  databaseconnect.py
Labels: beginner, gssoc20

#104 Removing the StanfordCoreNLP pre-requisite when using Docker #99 resolved
  Dockerfile
  ENV/.env
  ENV/docker.env
  README.md
  config.py
  docker-compose.yml
  docker-entrypoint.sh
  template.txt
Labels: gssoc20, hard

#96 Add method to googleMapsApiModule.py for PlaceSearchAPI #18 resolved
  googleMapsApiModule.py
Labels: gssoc20, medium

#98 Setup Travis CI_resolved
  .travis.yml
  app.py
  chatbot.py
  config.py
  constants.py
  databaseconnect.py
  features.py
  featuresDump.py
  googleMapsApiModule.py
  init.py
  test_googleMapsApiModule.py
  utilities.py
Labels: gssoc20, medium
